name: Markdown Linting

on:
  push:
    branches:
      - main # Change this to your main branch name, if different
  pull_request:
    branches:
      - main # Change this to your main branch name, if different

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli

    - name: Lint Markdown files
      run: markdownlint '**/*.md'
