name: Markdown Linting

on:
  push:
    branches:
      - '*' # Change this to your main branch name, if different
  pull_request:
    branches:
      - '*' # Change this to your main branch name, if different

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/checkout@main
      with:
        node-version: 16 # Use Node.js version 16

    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli

    - name: Lint Markdown files
      run: markdownlint '**/*.md'
