name: markdown_lint

on:
  push:
    branches:
      - '**'

jobs:
  markdown_lint:
    name: Check Markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Markdown Lint - check only 'docs' directory and exclude CHANGELOG.md
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          search_paths: |
            docs/
          exclude: |
            CHANGELOG.md

      - name: Markdown Lint - simple example
        uses: ruzickap/action-my-markdown-linter@v1

      - name: Markdown Lint using pre-built container
        uses: avto-dev/markdown-lint@v1
